### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by TheKotti** [OrfeasZ/Statman#19]
Good chance the problem is me, but I'm having issues getting the project to build as it should. After updating Statman project's .NET Framework to 4.8 and retargeting Pipeman and HM3 to v143, I still get errors trying to build HM3, leading to the application crashing as soon as it hooks into the game. Is this a problem with the updated tools or am I forgetting to do something? Could the projects be updated for more modern tools or instructions to be added to the README?

The errors when building HM3:
![image](https://github.com/user-attachments/assets/b82b5fac-121f-42e0-b472-ff092903e825)

**Comment by OrfeasZ** [comment]
Fixed.
